### PR TITLE
Added 'About' page to settings menu

### PR DESCRIPTION
**Pull request by stuarthayhurst**
## Changes:
 - Adds 7 new translation strings (sorry)
 - Adds an 'About' page to the settings menu that displays credits, a GitHub link, an icon, extension name, description, version and license information

@daPhipz 
The main reason for making a pull request on my own repository was to check that you're okay with your name and email on display on the about page, as you're listed as a translator. If you're okay with that, I'll merge this pr.

image
image
image

### CODE REVIEW

**Comment by stuarthayhurst** [comment]
The only think I'm unsure about is whether or not to keep the bottom text as well

**Comment by daPhipz** [comment]
> Adds 7 new translation strings
That's nothing you need to say sorry for ;)

Oooh, that `Gtk.AboutDialog` thingy looks very nice, I like it!
I don't mind being mentioned there, in fact I contribute translations to many GNOME applications. My name is in many of these dialogues, I imagine xD

> The only think I'm unsure about is whether or not to keep the bottom text as well

I wouldn't - the information is already in the About dialogue (the best place for it) and it makes the UI look a bit "unclean" if you know what I mean. But ultimately, it's up to you!

Have you come across a way on adding client-side decorations to the window's titlebar? I think it would be awesome to be able to access the About dialogue via a little (i) in the top left corner, like in the GNOME Extensions window

**Comment by stuarthayhurst** [comment]
> Have you come across a way of adding client-side decorations to the window's titlebar? I think it would be awesome to be able to access the About dialogue via a little (i) in the top left corner, like in the GNOME Extensions window

That was my original plan, but I don't think the `Gtk.ApplicationWindow` object is accessible from the extension, which I'd need access to add a button to the header.
I'll tweak the label text or remove it and then merge this, thanks for your input :)

**Comment by daPhipz** [comment]
@stuarthayhurst Have a look at this here: https://gjs.guide/extensions/overview/anatomy.html#prefs-js
They claim to be able to change the text of the headerbar, maybe this leads somewhere? I can't understand this unfortunately, and when simply copy-pasting it in, it throws an error that `GLib.timeout_add()` requires "At least 3 arguments, but only 2 passed". [Here](https://developer.gnome.org/pygobject/stable/glib-functions.html#function-glib--timeout-add) is the documentation of said function.

**Comment by stuarthayhurst** [comment]
This line `let headerBar = window.get_titlebar();` is interesting, it should give me access to the header bar as an object, so I'll be able to add a new element to it and link it to the about page.

**Comment by stuarthayhurst** [comment]
> [Here](https://developer.gnome.org/pygobject/stable/glib-functions.html#function-glib--timeout-add) is the documentation of said function.

I found the GJs docs [here](https://gjs-docs.gnome.org/glib20~2.66.1/glib.timeout_add), we need to add another argument for priority, then it's just a matter of modifying the header bar

**Comment by stuarthayhurst** [comment]
Working now, I can change the title to anything, so I can probably add that new element and link it to the actions menu. The code required was:
```
  GLib.timeout_add(0, 0, () => {
    let window = settings.widget.get_toplevel();
    let headerBar = window.get_titlebar();
    headerBar.title = 'Preferences';
       
    return GLib.SOURCE_REMOVE;
  });
```

**Comment by stuarthayhurst** [comment]
I've got a working button on the top bar now, just got to do some cleanup of the UI, assign an icon and tidy up the code, but I'll commit this soon :)

**Comment by daPhipz** [comment]
Nice! Looking forward to test it and learn how to implement this myself 🎉☺️

**Comment by stuarthayhurst** [comment]
I can't seem to get the icon to be a sensible size, it's constantly filling the entire button
I'm using the following:
```
function buildPrefsWidget() {
  let settingsMenu = new PrefsWidget();
  settingsMenu.widget.show_all();

  GLib.timeout_add(0, 0, () => {
    let window = settingsMenu.widget.get_toplevel();
    let headerBar = window.get_titlebar();

    //Create a button on the header bar and show the about menu when clicked
    let aboutButton = Gtk.Button.new_from_icon_name('dialog-information-symbolic', 16);
    aboutButton.connect('clicked', () => {
      settingsMenu.showAbout();
    });

    //Modify header bar title and add about menu button
    headerBar.title = _('Alphabetical App Grid Preferences');
    headerBar.pack_start(aboutButton);
    aboutButton.show_all();

    return GLib.SOURCE_REMOVE;
  });

  return settingsMenu.widget;
}
```
Everything is working, except the size of the icon:

image

**Comment by stuarthayhurst** [comment]
The about button in the bottom left has been removed, just not in that screenshot

**Comment by daPhipz** [comment]
Could you push the branch to this repo and file a PR to master? Maybe I can find a solution to make the icon smaller...

**Comment by stuarthayhurst** [comment]
I'm not at my computer right now, but I can do that tomorrow, although I'll start working on it again tomorrow. The code I've posted so far is a drop-in replacement for buildPrefsWidget, and the code inside the connection to the 'clicked' event of _aboutButton in class PrefsWidget on master should be exposed as showAbout(). The js code to link to the about button on the ui can also be commented out for testing. With those changes, you'll be able to more or less replicate my uncommitted changes.

**Comment by stuarthayhurst** [comment]
From memory, the class should be like:
```
var PrefsWidget = class PrefsWidget {
  constructor() {
    this._settings = ExtensionUtils.getSettings('org.gnome.shell.extensions.alphabetical-app-grid');

    this._builder = new Gtk.Builder();
    this._builder.set_translation_domain(Me.metadata.uuid);
    this._builder.add_from_file(Me.path + '/prefs.ui');

    this.widget = new Gtk.ScrolledWindow();
    this.widget.add(this._builder.get_object('main-prefs'));

    this._foldersSwitch = this._builder.get_object('sort-folders-switch');
    //Set sliders to match the gsettings vlaues for the extension
    this._updateSwitch(this._foldersSwitch, 'sort-folder-contents');
    //Update gsettings values when switches are toggled
 
  this._listenForChanges(this._foldersSwitch, 'sort-folder-contents');
}

  showAbout() {
    let aboutDialog = new Gtk.AboutDialog({
      authors: [
        'Stuart Hayhurst <stuart.a.hayhurst@gmail.com>'
      ],
      //Translators: Do not translate literally. If you want, you can enter your
      //contact details here: "FIRSTNAME LASTNAME <email@addre.ss>, YEAR."
      //If not, "translate" this string with a whitespace character.
      translator_credits: _('translator-credits'),
      program_name: _('Alphabetical App Grid'),
      comments: _('Restore the alphabetical ordering of the app grid'),
      license_type: Gtk.License.GPL_3_0,
      copyright: _('© 2021 Stuart Hayhurst'),
      logo: GdkPixbuf.Pixbuf.new_from_file_at_size(Me.path + '/icon.svg', 128, 128),
      version: 'v' + Me.metadata.version.toString(),
      website: Me.metadata.url.toString(),
      website_label: _('Contribute on GitHub'),
        modal: true
    });
    aboutDialog.present();
  }

  _listenForChanges(targetSwitch, gsettingsKey) {
    //Update gsettings value when switch is toggled
    targetSwitch.connect('state-set', () => {
      this._settings.set_boolean(gsettingsKey, targetSwitch.get_active());
    });
  }

  //Requires the element to toggle and the gsettings key to base it off of
  _updateSwitch(targetSwitch, gsettingsKey) {
    targetSwitch.set_active(this._settings.get_boolean(gsettingsKey));
  }
}

function init() {
  ExtensionUtils.initTranslations();
}
```

**Comment by stuarthayhurst** [comment]
If we can't find a solution, I guess we could always just label it 'About'.

**Comment by stuarthayhurst** [comment]
I made that pull request now (#14)

**Pull request merged**
