### PR TITLE
Complete Makefile rewrite

### PR DESCRIPTION
**Pull request by daPhipz**
## Pull request summary

This is a complete `Makefile` rewrite, which now takes more advantage of `make`'s capabilities.
To be honest, I took this as an opportunity to learn more about `make` and just wanted to work on a "real" thing when applying the things I learned xD
If this doesn't suit your style of doing things, feel free to not merge this PR - it was worth it for me regardless :wink:

## Build system related changes

Many.
Instead of explaining what changed exactly, I'll just explain what the different targets in the new `Makefile` do now. In everyday development, you'll only need the `PHONY` targets, anything else is behind the scenes stuff.

### General `Makefile` syntax

- The `@` sign in front of a command stops it from being printed to stdout by `make`, leaving only the actual command output.
- `$@` refers to the target of a rule.
- `$<` refers to the first prerequisite of a rule.
- `$$` escapes the second dollar sign for `make` and passes it on to bash.
- `%` is like `*` in `bash`.

### PHONY targets

These are meant to be run by the developer.

#### `build`
Build the extension.

#### `release`
Build the extension and additionally run the pre-release checks.

#### `install`
Build the extension and install it to the system.

#### `uninstall`
Uninstall the extension. Duh.

#### `all-po`
Update all `po` files with the latest strings. Handles potentially necessary `pot` file updates automatically, before actually updating the `po` files.

### Regular targets
These are meant to be executed automatically, not by the developer.

#### `AlphabeticalAppGrid@stuarthayhurst.shell-extension.zip`
If any of the prerequisites (or prerequisites for prerequisites for prerequisites etc etc) changed, build the zip.
I used two `zip` commands to be able to put some files in the `zip`'s root, even if they are not in the project root.

#### `schemas/gschemas.compiled`
If `schemas/org.gnome.shell.extensions.AlphabeticalAppGrid.gschema.xml` changed, update `schemas/gschemas.compiled`.

#### `build/%.png`
If `docs/%.png` changed, optimize it with `optipng` and save it to `build/`. This is a sort of temporary directory that is not included in the source tree (see `.gitignore`) and holds the optimized version of the `png`s.

#### `ui/prefs-gtk4.ui`
If `prefs.ui` changed, update its GTK4 version.

#### `%.mo`
If a `po` file or `messages.pot` changed, compile the new translations. In order for this to work, I had to restructure the translation files a little bit.

#### `%.po`
If `locale/messages.pot` changed, update `%.po`.

#### `locale/messages.pot`
If any `*.js` or `*.ui` files changed, update the `pot` file with the latest strings.

#### `clean`
Remove all build files and leave the raw source code behind.

## TODO
There is still some work left to do outside the `Makefile` - but since this was primarily intended for a bit of `make` practice, I wanted to hear your opinion on merging this first.

- [ ] Is `ui/prefs-gtk4.ui` really generated automatically 100%, or is any manual intervention needed?
- [ ] Update/delete translation scripts in `scripts/`
- [ ] Update `.github/workflows/test-build-system.yml`
- [ ] Update README.md
- [ ] Update CONTRIBUTING.md

### CODE REVIEW

**Comment by stuarthayhurst** [comment]
I'll be honest, this mostly isn't in my style, sorry.
However, after a quick skim read, I do believe there is still stuff here of value to the project.
When I wrote the Makefile initially, it was based off of the Makefile for another of my projects, which was based off of another project when I was still learning Bash, so I'm not surprised it could use some work.
I noticed some of the work seemed to be around grouping things together and automating workflows. I left it a little less 'tied together', to allow for an easier entrypoint when attempting to debug certain parts.

Yes, `ui/prefs-gtk4.ui` is completely automatic, I initially planned on just using it to create a rough guide for the GTK 4 UI, but it worked flawlessly out of the box, and has done since. As I develop primarily on GNOME 40, it gets thoroughly tested, and if there's an issue I'll start manually correcting it. Depending on if / when glade supports GTK 4, and if / when I drop GNOME 38 support in this repo, the `gtk4` target may also be dropped in future.

Based off of what's already in the repository, I did think it might be a good idea to work on the following:
 - Better integration with Makefile's capabilities, which it seems you've done some work on in this PR. I'll take a look at this, seems useful :)
 - The automatic build system testing could be improved, I wrote it relatively quickly, again based off of another project I wrote
 - The scripts in `scripts` could probably be improved or updated, I just simplified the translation scripts a bit when you submitted them and haven't touched them since
 - I also like the changes to `.gitignore`. They're small, but still a nice bit of structure. If you liked, you could submit that as a PR, as long as it's updated to use the files currently affected the project's structure.

Considering the extent proposed changes and what I feel needed to be worked on, it may be worth starting again, if you wanted to work on this. I'd also appreciate it if each of the points mentioned above were separate PRs, as that makes managing the commits and progress of each easier.
Whatever the outcome of this is, I'm glad you found it useful for learning :D

**Comment by stuarthayhurst** [comment]
As it's probably worth making an issue for this, I'll summarise my last message in an issue, with a checklist. That way, this can be closed and it can all be tracked from the issue instead.

**Comment by daPhipz** [comment]
Thanks for your detailed feedback, I appreciate it :)
Your ideas are good, I am looking forward to working on them!
One thing that I learned about just now - it is possible to pass variables to `make`, which lets you do something like this:

```
make release VERSION="17"
```
We could then update the version number in `metadata.json` (I think this is the only place where it is, right?) for each release automatically - what do you think? Are there maybe other use cases for this as well?

**Comment by stuarthayhurst** [comment]
Oh that's a good idea, I'll add that to the issue when I make it later, I'll also see if I can find any other uses for that.

**Comment by stuarthayhurst** [comment]
Closed, as the points of improvement are outlined in #40 now

**Pull request closed without merging**
