### PR TITLE
Add copyright, licensing info and GitHub link to settings

### PR DESCRIPTION
**Pull request by daPhipz**
As the title says.

Do you find a more elegant solution for adding padding to the left/right of the setting label/the switch? I did it like this because if I'd add padding to the `GtkListBox` itself, the background of the `GtkListBoxRow` wouldn't go to the edge of the window - looks not nice.

If we keep it like this, we would have to do it for every new row in the `GtkListBox` again. Not really that big of a deal imo, but a more elegant solution would still be cool...

### CODE REVIEW

**Comment by stuarthayhurst** [comment]
I'm not very familiar with using GTK+ in programming, I don't really know how to do anything without hours of hitting rocks together... I like the styling of the extensions app, so if we could replicate something like that, that would be great.

image

**Comment by stuarthayhurst** [comment]
The german translation is still needed, and I'm happy to merge unless you want to make more changes. I think any new UI changes should probably go into a new pull request.

**Comment by daPhipz** [comment]
Good idea to mimic the style of the Extensions app, I like it as well!

I can have a go at it, but I'm definitely not more experienced with designing Gtk UIs than you xD
It might take some time, but we'll get there eventually.

Translation done, I am happy to merge!

PS: I noticed that you reverted the line breaks in the `msgstr`s - was this on purpose? I use [Poedit](https://poedit.net/) to do the translations and it auto-inserts line breaks every ~80 characters or so. With short lines, git is more efficient in detecting changes.

**Comment by stuarthayhurst** [comment]
Ohh, I reverted those line breake because I thought I messed it up, I wondered why they kept reappearing. I'll create an issue for the UI design tomorrow and try and come up with something.

**Pull request merged**
